apiVersion: v1
kind: Pod
metadata:
  name: volume-share-nautilus
spec:
  containers:
  - name: volume-container-nautilus-1
    image: debian:latest
    command: ["sleep", "10m"]
    volumeMounts:
      - name: volume-share
        mountPath: "/tmp/blog"
  - name: volume-container-nautilus-2
    image: debian:latest
    command: ["sleep", "10m"]
    volumeMounts:
      - name: volume-share
        mountPath: "/tmp/cluster"
  volumes:
    - name: volume-share
      emptyDir: {}