apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
    run: jekyll
spec:
  initContainers:
    - name: copy-jekyll-site
      image: gcr.io/kodekloud/customimage/jekyll
      command:
        - /bin/sh
        - -c
        - "rm -rf /site/* && jekyll new /site && cd /site && bundle install"
      volumeMounts:
        - name: site
          mountPath: /site
  containers:
    - name: jekyll
      image: gcr.io/kodekloud/customimage/jekyll-serve
      ports:
        - containerPort: 4000
      command:
        - /bin/sh
        - -c
        - "cd /site && bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 4000"
      volumeMounts:
        - name: site
          mountPath: /site
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site